# Generated by Django 4.0.6 on 2022-07-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eticket',
            name='column_no',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='eticket',
            name='row_no',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
