# Generated by Django 4.0.6 on 2022-07-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_eticket_column_no_eticket_row_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eticket',
            name='column_no',
        ),
        migrations.RemoveField(
            model_name='eticket',
            name='row_no',
        ),
        migrations.AddField(
            model_name='reservation',
            name='column_no',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='row_no',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
