# Generated by Django 4.0.6 on 2022-07-24 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_venue_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='category',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='number_of_seats',
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.CharField(choices=[('VVIP', 'VVIP'), ('VIP', 'VIP'), ('REGULAR', 'REGULAR'), ('KIDS', 'KIDS'), ('ADVANCED', 'ADVANCED')], default='REGULAR', max_length=20)),
                ('number_of_seats', models.PositiveIntegerField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.venue')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='available_slots',
            field=models.ManyToManyField(blank=True, null=True, to='tickets.slot'),
        ),
    ]
