# Generated by Django 4.0.6 on 2022-08-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_eticket_column_no_remove_eticket_row_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='owner',
        ),
    ]
