# Generated by Django 4.0.6 on 2022-07-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_event_available_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='name',
        ),
    ]
