# Generated by Django 4.0.6 on 2022-07-24 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_slot_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='venue',
            new_name='theatre',
        ),
    ]
