# Generated by Django 4.0.6 on 2022-07-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_rename_venue_slot_theatre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='category',
            field=models.CharField(blank=True, choices=[('VVIP', 'VVIP'), ('VIP', 'VIP'), ('REGULAR', 'REGULAR'), ('KIDS', 'KIDS'), ('ADVANCED', 'ADVANCED')], default='REGULAR', max_length=20, null=True),
        ),
    ]
