# Generated by Django 4.0.6 on 2022-07-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_slot_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='theatre',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
