# Generated by Django 4.0.6 on 2022-07-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_slot_theatre'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='starting_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='available_slots',
            field=models.ManyToManyField(to='tickets.slot'),
        ),
    ]
