# Generated by Django 4.0.6 on 2022-07-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_remove_ticket_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_slots',
            field=models.ManyToManyField(blank=True, to='tickets.slot'),
        ),
    ]
