# Generated by Django 4.0.6 on 2022-07-25 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_event_available_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='paid',
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.paymentcategories'),
        ),
    ]
