# Generated by Django 4.0.6 on 2022-07-26 07:38

from django.db import migrations
import inclusive_django_range_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_remove_ticket_paid_ticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='seat_numbers',
            field=inclusive_django_range_fields.fields.InclusiveIntegerRangeField(blank=True, null=True),
        ),
    ]
