# Generated by Django 4.0.6 on 2022-07-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_slot_seat_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='seat_numbers',
        ),
        migrations.AddField(
            model_name='slot',
            name='from_seat_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='to_seat_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
