# Generated by Django 4.0.6 on 2022-07-26 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_remove_slot_seat_numbers_slot_from_seat_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Eticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(blank=True, max_length=20, null=True)),
                ('ticket_class', models.CharField(blank=True, max_length=20, null=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.reservation')),
            ],
        ),
    ]
