# Generated by Django 4.0.6 on 2022-07-26 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_reservation_paid_eticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eticket',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tickets.reservation'),
        ),
    ]
